from_date_locator = "xpath://input[@id='fromdate']"
to_date_locator = "xpath://input[@id='todate']"
no_of_records_locator = "xpath://select[@id='ddlRecordNum']"
select_companies_locator = "xpath://select[@id='ddCompanies']"
all_table_row_locator = "xpath://table[@class='table table-fixed']/tbody/tr"
all_table_column_locator = "xpath://table[@class='table table-fixed']/thead/tr/th"
trans_refGUID_column_locator = "xpath://table[@class='table table-fixed']/tbody/tr/td[7]"
table_body_xpath_locator = "xpath://table[@class='table table-fixed']/tbody"
refreshButton = "xpath:(//input[@id='btRefresh'])[1]"
