zl_user_input = "//input[@id='username']"
zl_user_pass_input = "//input[@type='password']"
zl_user_submit_btn = "//button[@type='submit']"
zl_user_pass_submit_btn = "//input[@type='submit']"
policy_search_input = "//input[@placeholder='Policy or contract number']"
middle_name_bene_change_inout = "//input[@aria-label='Middle name']"
sign_date_input = "//input[@aria-label='Sign date']"
policy_search_btn = "//button[@aria-label='Search']"
search_result_select = "//a[@class='policy-row_policyLink__FkzFu']"
policy_tab = "//a[normalize-space()='Policy']"
people_tab = "//a[normalize-space()='People']"
people_owner_payee_select = "//div[@class='prose flex content-center justify-between']"
manage_bene_select = "//button[normalize-space()='Manage beneficiaries']"
owner_tab_select = "//button[@value='OWNER']"
bene_tab_select = "//button[@value='beneficiary']"
communication_edit_btn = "//div[@class='flex items-center gap-2 !gap-1']//button[@type='button']//*[name()='svg']"
contract_tab = "//a[normalize-space()='Contract']"
loans_tab = "//p[normalize-space()='Loans']"
withdrawal_tab = "//p[normalize-space()='Withdrawals']"
premium_tab = "//p[normalize-space()='Premiums']"
validate_premium_setup = "//div[normalize-space()='$300.00']"
allocation_submit_btn = "(//button[normalize-space()='Submit'])[1]"
fund_account_tab = "//p[normalize-space()='Funds and Accounts']"
transfer_fund_value_btn = "//a[@class='nav-element_navLink__xaeTo text-links default-focus focus-visible:rounded undefined text-links-sm']"
start_loan_btn = "//a[@class='nav-element_navLink__xaeTo text-links default-focus focus-visible:rounded mr-5 text-links-sm']"
process_without_document_txt = "//span[normalize-space()='Process without a document']"
preferred_comm_type = "//button[normalize-space()='Save Preferred Communication']"
email_com_select = "(//div[normalize-space()='Personal'])[3]"
residence_com_select = "(//div[normalize-space()='Residence'])[1]"
update_allocation_btn = "//button[normalize-space()='Update allocations']"
fix_fund_allocation_percent = "(//div[@class='flex grow flex-row items-center justify-between'])[2]"
test = "(//input[@aria-label = 'Input Field'])[1]"
test1 = "(//input[@aria-label = 'Input Field'])[2]"
test2 = "(//input[@aria-label = 'Input Field'])[3]"
cap_amount_allocation_percent = "(//input[@class='text-right w-full w-full border-0 bg-transparent p-0 font-secondary text-md font-normal leading-5.5 !outline-none !ring-0 px-4 py-2 cursor-auto'] )[2]"
participation_allocation_rate_percent = "(//input[@class='text-right w-full w-full border-0 bg-transparent p-0 font-secondary text-md font-normal leading-5.5 !outline-none !ring-0 px-4 py-2 cursor-auto'] )[3]"
cancel_autopay_checkbox = "//div[@class='relative flex']"
continue_btn = "//button[@data-testid='Continue']"
designation_select = "//button[@aria-label='Designation']"
sign_present_select = "//button[@aria-label='Sign present']"
assignee_select = "//p[normalize-space()='Assignee']"
sign_present_slct = "//p[normalize-space()='Yes']"
primary_bene_extend = "//div[@class='ml-6']//*[name()='svg']"
continue_doc_btn = "//button[@aria-label='Continue']"
continue_button = "//button[normalize-space()='Continue']"
transfer_form_fund_select = "(//p[normalize-space()='--Select fund--'])[1]"
transfer_to_fund_select = "(//p[normalize-space()='--Select fund--'])[1]"
transfer_cap_account_select = "//p[normalize-space()='S&P 500® Price Return Annual Point-to-Point with Cap Account']"
transfer_to_rate_account_select = "//p[normalize-space()='S&P 500® Price Return Annual Point-to-Point with Participation Rate Account']"
transfer_from_amount_input = "(//input[@aria-label='Input Field'])[1]"
transfer_to_amount_input = "(//input[@aria-label='Input Field'])[2]"
withdrawal_type_btn = "//span[@data-label='Withdrawal']"
rmd_type_btn = "//span[@data-label='RMD']"
cancel_autppay_btn = "//button[normalize-space()='Cancel autopay']"
autopay_payment_start_date = "//input[@data-testid='Payment start date']"
manage_payment_next_payment_date = "//input[@data-testid='Next payment date']"
autopay_payment_method_continue_btn = "//button[normalize-space()='Continue']"
payment_page_continue_btn = "//button[@data-testid='continue-button']"
custom_amount_radio_btn = "//input[@id='radio-undefined-0-']"
custom_amount_input = "//input[@aria-label='Custom amount']"
payee_tab = "//div[@class='p-4']"
payment_mode_select = "//button[@value = '{}']"
banking_details_tab = "//div[@class='mb-4 flex flex-col items-start']"
validate_loan_amt_text = "//span[normalize-space()='{}']"
validate_systematic_premium = "//div[normalize-space()='{}']"
validate_effective_date = "//span[normalize-space()='{}']"
validate_fund_allocation = "//p[normalize-space()='{}']"
validate_payee_name = "//span[normalize-space()='{}']"
validate_fix_fund_allocation_percent = "//p[normalize-space()='{}']"
validate_payment_method = "//div[normalize-space()='{}']"
update_loan_loan_autoPay_submit_btn = "//button[normalize-space()='Update loan autopay']"
validate_account_name = "//span[normalize-space()='{}']"
validate_transfer_from = "//td[normalize-space()='{}']"
validate_transfer_to = "//td[normalize-space()='{}']"
validate_account_number = "//span[contains(text(), '{}')]"
loan_submit_checkbox = "//input[@type='checkbox']"
loan_submit_btn = "//button[@aria-label='Submit loan']"
one_time_loan_repayment_btn = "//a[normalize-space()='Make one-time payment']"
one_time_loan_payment_input = "//input[@aria-label='Loan payment amount']"
payment_method_txt = "//h1[normalize-space()='Payment Method']"
one_time_submit_payment_btn = "//button[@aria-label='Submit payment']"
onr_time_payment_method_continue_btn = "//button[normalize-space()='Continue']"
validate_start_loan_apply = "//button[normalize-space()='Go to case']"
setup_auto_pay_btn = "(//a[normalize-space()='Set up autopay'])[1]"
setup_auto_rmd_pay_btn = "(//a[normalize-space()='Set up autopay'])[2]"
systematic_manage_autopay_btn = "//a[normalize-space()='Manage autopay']"
manage_autopay_btn = "//a[normalize-space()='Manage autopay']"
cancel_autopay_btn = "//a[normalize-space()='Cancel autopay']"
edit_allocation_btn = "//label[@class='tracking-normal no-underline typography-labels-label cursor-pointer']"
loan_auto_pay_amount_input = "(//div[@class= 'flex grow flex-row items-center justify-between'])[1]"
loan_auto_amount_input = "//input[@aria-label='Loan autopay amount']"
systematic_loan_auto_pay_input = "//input[@aria-label = 'Amount']"
payment_frequency_radio_btn = "//label[normalize-space()='{}']/preceding-sibling::input[@type='radio']"
submit_payment_btn = "//button[normalize-space()='Submit payment']"
update_premium_autopay_btn = "//button[normalize-space()='Update premium autopay']"
go_to_case_btn = "//button[normalize-space()='Go to case']"
validate_zinnia_complete_status = "//span[@class = '_badge_1fqps_1 _success_1fqps_17' and normalize-space()='Completed']"
validate_zinnia_nigo_status = "//span[normalize-space()='Not in good order']"
start_loan_date_btn = "//div[@class='text-link mr-4']"
month_select = "//div[@class='flex flex-row justify-between text-gray-900']//div[2]"
feb_month_select = "//p[normalize-space()='Feb']"
back_date_btn = "//div[@class='flex flex-row justify-between text-gray-900']//div[1]"
start_loan_date_select = "//div[19]"
payment_start_date = "//div[09]"
systematic_withdrawal_effective_start_date = "//div[17]"
start_loan_effective_date = "//input[@aria-label = 'Effective date']"
continue_button = "//button[normalize-space()='Continue']"
select_signature_tab = "//span[normalize-space()='Signature']"




case_id_select = "//tr[@class='_tableRow_58wmn_25 case-result-table_row__9xfx6']"
zl_progress_txt = "//span[contains(text(), 'Case Details')]"
Validate_application_expands_menu = "//label[contains(text(), 'Validate application')]"
zl_Validate_suitability_txt = "//label[contains(text(), 'Validate suitability')]"
zl_nb_attachment_nigo_txt = "//span[contains(text(), 'NB Attachment Nigo')]"
zl_application_nigo_txt = "//span[contains(text(), 'Application Nigo')]"
zl_login_welcome_txt = "//h1[contains(text(), 'Welcome')]"
zl_case_managment_txt = "//h1[contains(text(), 'Case Management')]"
zl_policy_search_tab = "//span[normalize-space()='Policies & Contracts']"



